### ISSUE TITLE
'RCC_CSR_LSIRDY' undeclared (first use in this function)

### ISSUE THREAD

**Issue by RotemShechterN** [jefftenney/LPTIM-Tick-U5#7]
When trying to compile with LSI clock on STM32U585 the following error occurs: 'RCC_CSR_LSIRDY' undeclared (first use in this function) 
```
129#ifdef configTICK_USES_LSI
130  #define LPTIMSEL_Val 1 // LSI
131   #define IS_REF_CLOCK_READY() (RCC->CSR & RCC_CSR_LSIRDY)
```

looking up for STM32U5 reference design seems like there is no such a bit.

**Comment by jefftenney** [comment]
Fixed in [5222d64](https://github.com/jefftenney/LPTIM-Tick-U5/commit/5222d645a1e8a3593e9a8c7d0780fd174543e676).  Thanks @RotemShechterN!
